BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SPI FTOLED SD digitalWriteFast

ARDUINO_DIR ?= /usr/share/arduino
ARDMK_DIR     ?= /usr
AVR_TOOLS_DIR ?= /usr

include ${ARDUINO_DIR}/Arduino.mk
CPPFLAGS += -Wall -Werror
